### PR TITLE
License Agreement

### PR DESCRIPTION
**Pull request by hfanan**

### CODE REVIEW

**Comment by hfanan** [comment]
@microsoft-github-policy-service agree company="Pure Storage"

**Comment by hfanan** [comment]
@microsoft-github-policy-service agree company="Pure Storage"


------ Original Message ------
From "microsoft-github-policy-service[bot]" ***@***.***>
To "Azure/Microsoft.AVS.Management" 
***@***.***>
Cc "Hesham Anan" ***@***.***>; "Mention" ***@***.***>
Date 3/27/2023 4:26:02 PM
Subject Re: [Azure/Microsoft.AVS.Management] License Agreement (PR #159)

**Comment by et1975** [comment]
What's the motivation for this change?

**Comment by hfanan** [comment]
> What's the motivation for this change?

To accept license agreement. main driver is Pull Request 158 which is used to add needed RunCommand in Microsoft.AVS.VMFS

**Pull request closed without merging**
